#pragma once
#include <utility/cuda/system.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <sstream>
#include <string>
#include <utility/identifier/arrays.h>
#include <utility/identifier/uniform.h>
#include <utility/cuda/memory.h>
#include <utility/cuda/error_handling.h>
#include <utility/cuda/system.h>
#include <utility/cuda/cache.h>