#pragma once
#include <utility/mathv2/baseTypes.h>
#include <utility/mathv2/ratio.h>
#include <utility/mathv2/detection.h>
#include <utility/mathv2/unit_types.h>
#include <utility/mathv2/tools.h>
#include <utility/mathv2/unit_typedefs.h>
#include "utility/mathv2/functions.h"
#include "utility/mathv2/operators.h"